apiVersion: v1
kind: Secret
metadata:
  name: basic-node-app-secret
  labels:
    name: basic-node-js-app
type: kubernetes.io/basic-auth #You can mention type as per your need https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
# Alternatively you can also use "data" block as mentioned below. In that case you will need to mount the secret by yourself.
stringData:
  username: admin
  password: t0p-Secret
#data:
# username: YWRtaW4= #Need to be Base64 Encoded
# password: dDBwLVNlY3JldA== #Need to be Base64 Encoded